"""empty message

Revision ID: 3bc9aa7df7e9
Revises: ac44b30d32d3
Create Date: 2024-08-22 00:13:09.379056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc9aa7df7e9'
down_revision = 'ac44b30d32d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone_num', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salt', sa.String(length=180), nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('public_id_avatar', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('update_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('update_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('public_id_avatar')
        batch_op.drop_column('avatar')
        batch_op.drop_column('salt')
        batch_op.drop_column('phone_num')
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
