"""empty message

Revision ID: 5fcb85348f0e
Revises: 11314be6e271
Create Date: 2024-09-07 21:47:12.268788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fcb85348f0e'
down_revision = '11314be6e271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_status_change_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_status_change_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['last_status_change_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_status_change_at')
        batch_op.drop_column('last_status_change_by')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
